

version: '3.8'

services:
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "#admin#"  
      GF_SERVER_ROOT_URL: "http://localhost:3000/"
    networks:
      - grafana-network

volumes:
  grafana-storage:
    driver: local

networks:
  grafana-network:
    driver: bridge

    