  
  
services:
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "#admin#"  
      GF_SERVER_ROOT_URL: "http://localhost:3000/"
    networks:
      - grafana-network

  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - grafana-network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.3
    container_name: nginx-exporter
    depends_on:
      - nginx
    environment:
      - NGINX_PROMETHEUS_EXPORTER_URL=http://nginx:80/status
    command:
      - --nginx.scrape-uri=http://nginx:80/status
    ports:
      - "9113:9113"
    networks:
      - grafana-network

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - grafana-network

  nginx:
    image: nginx:1.26.1
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html  
    networks:
      - grafana-network

  webhook:
    image: python:3.9-slim
    container_name: webhook
    volumes:
      - ./webhook:/webhook
    working_dir: /webhook
    command: python app.py
    networks:
      - grafana-network

volumes:
  grafana-storage:
    driver: local

networks:
  grafana-network:
    driver: bridge
